import './cars.dart';
import './tracks.dart';

class FuelUsageType {
  const FuelUsageType(this.carKsName, this.trackKsName, this.fuelUsage);

  final String carKsName;
  final String trackKsName;
  final double fuelUsage;
}

double getFuelUsageDefault(Car car, Track track)
{
  for (FuelUsageType fuelUsageItem in fuelUsageDefaultList)
    if ((fuelUsageItem.carKsName == car.ksName) && (fuelUsageItem.trackKsName == track.ksName))
      return fuelUsageItem.fuelUsage;

  return 1.0;
}

const List<FuelUsageType> fuelUsageDefaultList = [
  FuelUsageType('amr_v12_vantage_gt3', 'monza',         3.67),
  FuelUsageType('amr_v12_vantage_gt3', 'Brands_Hatch',  3.00),
  FuelUsageType('amr_v12_vantage_gt3', 'Silverstone',   3.60),
  FuelUsageType('amr_v12_vantage_gt3', 'Paul_Ricard',   3.60),
  FuelUsageType('amr_v12_vantage_gt3', 'misano',        2.86),
  FuelUsageType('amr_v12_vantage_gt3', 'zandvoort',     2.90),
  FuelUsageType('amr_v12_vantage_gt3', 'Spa',           4.37),
  FuelUsageType('amr_v12_vantage_gt3', 'nurburgring',   3.36),
  FuelUsageType('amr_v12_vantage_gt3', 'hungaroring',   2.90),
  FuelUsageType('amr_v12_vantage_gt3', 'barcelona',     3.05),
  FuelUsageType('amr_v12_vantage_gt3', 'zolder',        2.75),
  FuelUsageType('amr_v12_vantage_gt3', 'mont_panorama', 3.70),
  FuelUsageType('amr_v12_vantage_gt3', 'Laguna_Seca',   2.40),
  FuelUsageType('amr_v12_vantage_gt3', 'Suzuka',        3.25),
  FuelUsageType('amr_v12_vantage_gt3', 'Kyalami',       2.90),

  FuelUsageType('amr_v8_vantage_gt3', 'monza',         3.25),
  FuelUsageType('amr_v8_vantage_gt3', 'Brands_Hatch',  2.40),
  FuelUsageType('amr_v8_vantage_gt3', 'Silverstone',   3.36),
  FuelUsageType('amr_v8_vantage_gt3', 'Paul_Ricard',   3.26),
  FuelUsageType('amr_v8_vantage_gt3', 'misano',        2.65),
  FuelUsageType('amr_v8_vantage_gt3', 'zandvoort',     2.60),
  FuelUsageType('amr_v8_vantage_gt3', 'Spa',           3.90),
  FuelUsageType('amr_v8_vantage_gt3', 'nurburgring',   2.90),
  FuelUsageType('amr_v8_vantage_gt3', 'hungaroring',   2.60),
  FuelUsageType('amr_v8_vantage_gt3', 'barcelona',     2.75),
  FuelUsageType('amr_v8_vantage_gt3', 'zolder',        2.50),
  FuelUsageType('amr_v8_vantage_gt3', 'mont_panorama', 3.70),
  FuelUsageType('amr_v8_vantage_gt3', 'Laguna_Seca',   2.40),
  FuelUsageType('amr_v8_vantage_gt3', 'Suzuka',        3.30),
  FuelUsageType('amr_v8_vantage_gt3', 'Kyalami',       2.60),

  FuelUsageType('audi_r8_lms_evo', 'monza',         3.23),
  FuelUsageType('audi_r8_lms_evo', 'Brands_Hatch',  3.00),
  FuelUsageType('audi_r8_lms_evo', 'Silverstone',   3.18),
  FuelUsageType('audi_r8_lms_evo', 'Paul_Ricard',   3.18),
  FuelUsageType('audi_r8_lms_evo', 'misano',        2.60),
  FuelUsageType('audi_r8_lms_evo', 'zandvoort',     3.00),
  FuelUsageType('audi_r8_lms_evo', 'Spa',           3.90),
  FuelUsageType('audi_r8_lms_evo', 'nurburgring',   3.00),
  FuelUsageType('audi_r8_lms_evo', 'hungaroring',   2.65),
  FuelUsageType('audi_r8_lms_evo', 'barcelona',     2.77),
  FuelUsageType('audi_r8_lms_evo', 'zolder',        2.45),
  FuelUsageType('audi_r8_lms_evo', 'mont_panorama', 3.90),
  FuelUsageType('audi_r8_lms_evo', 'Laguna_Seca',   2.61),
  FuelUsageType('audi_r8_lms_evo', 'Suzuka',        3.70),
  FuelUsageType('audi_r8_lms_evo', 'Kyalami',       3.00),

  FuelUsageType('bentley_continental_gt3_2018', 'monza',         3.30),
  FuelUsageType('bentley_continental_gt3_2018', 'Brands_Hatch',  2.70),
  FuelUsageType('bentley_continental_gt3_2018', 'Silverstone',   3.25),
  FuelUsageType('bentley_continental_gt3_2018', 'Paul_Ricard',   3.25),
  FuelUsageType('bentley_continental_gt3_2018', 'misano',        2.60),
  FuelUsageType('bentley_continental_gt3_2018', 'zandvoort',     2.80),
  FuelUsageType('bentley_continental_gt3_2018', 'Spa',           4.00),
  FuelUsageType('bentley_continental_gt3_2018', 'nurburgring',   3.10),
  FuelUsageType('bentley_continental_gt3_2018', 'hungaroring',   2.80),
  FuelUsageType('bentley_continental_gt3_2018', 'barcelona',     2.70),
  FuelUsageType('bentley_continental_gt3_2018', 'zolder',        2.56),
  FuelUsageType('bentley_continental_gt3_2018', 'mont_panorama', 3.75),
  FuelUsageType('bentley_continental_gt3_2018', 'Laguna_Seca',   2.45),
  FuelUsageType('bentley_continental_gt3_2018', 'Suzuka',        3.55),
  FuelUsageType('bentley_continental_gt3_2018', 'Kyalami',       2.70),

  FuelUsageType('bmw_m6_gt3', 'monza',         3.50),
  FuelUsageType('bmw_m6_gt3', 'Brands_Hatch',  2.86),
  FuelUsageType('bmw_m6_gt3', 'Silverstone',   3.25),
  FuelUsageType('bmw_m6_gt3', 'Paul_Ricard',   3.23),
  FuelUsageType('bmw_m6_gt3', 'misano',        2.80),
  FuelUsageType('bmw_m6_gt3', 'zandvoort',     2.82),
  FuelUsageType('bmw_m6_gt3', 'Spa',           4.08),
  FuelUsageType('bmw_m6_gt3', 'nurburgring',   3.27),
  FuelUsageType('bmw_m6_gt3', 'hungaroring',   2.82),
  FuelUsageType('bmw_m6_gt3', 'barcelona',     2.86),
  FuelUsageType('bmw_m6_gt3', 'zolder',        2.67),
  FuelUsageType('bmw_m6_gt3', 'mont_panorama', 3.75),
  FuelUsageType('bmw_m6_gt3', 'Laguna_Seca',   2.45),
  FuelUsageType('bmw_m6_gt3', 'Suzuka',        3.55),
  FuelUsageType('bmw_m6_gt3', 'Kyalami',       2.86),

  FuelUsageType('jaguar_g3', 'monza',         3.70),
  FuelUsageType('jaguar_g3', 'Brands_Hatch',  3.20),
  FuelUsageType('jaguar_g3', 'Silverstone',   3.65),
  FuelUsageType('jaguar_g3', 'Paul_Ricard',   3.65),
  FuelUsageType('jaguar_g3', 'misano',        2.90),
  FuelUsageType('jaguar_g3', 'zandvoort',     2.95),
  FuelUsageType('jaguar_g3', 'Spa',           4.60),
  FuelUsageType('jaguar_g3', 'nurburgring',   3.50),
  FuelUsageType('jaguar_g3', 'hungaroring',   2.95),
  FuelUsageType('jaguar_g3', 'barcelona',     3.20),
  FuelUsageType('jaguar_g3', 'zolder',        2.80),
  FuelUsageType('jaguar_g3', 'mont_panorama', 4.00),
  FuelUsageType('jaguar_g3', 'Laguna_Seca',   2.70),
  FuelUsageType('jaguar_g3', 'Suzuka',        3.80),
  FuelUsageType('jaguar_g3', 'Kyalami',       3.20),

  FuelUsageType('ferrari_488_gt3', 'monza',         3.10),
  FuelUsageType('ferrari_488_gt3', 'Brands_Hatch',  2.61),
  FuelUsageType('ferrari_488_gt3', 'Silverstone',   3.00),
  FuelUsageType('ferrari_488_gt3', 'Paul_Ricard',   3.00),
  FuelUsageType('ferrari_488_gt3', 'misano',        2.49),
  FuelUsageType('ferrari_488_gt3', 'zandvoort',     2.55),
  FuelUsageType('ferrari_488_gt3', 'Spa',           3.70),
  FuelUsageType('ferrari_488_gt3', 'nurburgring',   2.88),
  FuelUsageType('ferrari_488_gt3', 'hungaroring',   2.55),
  FuelUsageType('ferrari_488_gt3', 'barcelona',     2.61),
  FuelUsageType('ferrari_488_gt3', 'zolder',        2.40),
  FuelUsageType('ferrari_488_gt3', 'mont_panorama', 3.55),
  FuelUsageType('ferrari_488_gt3', 'Laguna_Seca',   2.15),
  FuelUsageType('ferrari_488_gt3', 'Suzuka',        3.25),
  FuelUsageType('ferrari_488_gt3', 'Kyalami',       2.61),

  FuelUsageType('honda_nsx_gt3_evo', 'monza',         3.45),
  FuelUsageType('honda_nsx_gt3_evo', 'Brands_Hatch',  2.40),
  FuelUsageType('honda_nsx_gt3_evo', 'Silverstone',   3.55),
  FuelUsageType('honda_nsx_gt3_evo', 'Paul_Ricard',   3.45),
  FuelUsageType('honda_nsx_gt3_evo', 'misano',        2.66),
  FuelUsageType('honda_nsx_gt3_evo', 'zandvoort',     2.66),
  FuelUsageType('honda_nsx_gt3_evo', 'Spa',           4.10),
  FuelUsageType('honda_nsx_gt3_evo', 'nurburgring',   3.20),
  FuelUsageType('honda_nsx_gt3_evo', 'hungaroring',   2.71),
  FuelUsageType('honda_nsx_gt3_evo', 'barcelona',     2.85),
  FuelUsageType('honda_nsx_gt3_evo', 'zolder',        2.60),
  FuelUsageType('honda_nsx_gt3_evo', 'mont_panorama', 3.90),
  FuelUsageType('honda_nsx_gt3_evo', 'Laguna_Seca',   2.70),
  FuelUsageType('honda_nsx_gt3_evo', 'Suzuka',        3.70),
  FuelUsageType('honda_nsx_gt3_evo', 'Kyalami',       2.85),

  FuelUsageType('lamborghini_huracan_gt3_evo', 'monza',         3.29),
  FuelUsageType('lamborghini_huracan_gt3_evo', 'Brands_Hatch',  2.85),
  FuelUsageType('lamborghini_huracan_gt3_evo', 'Silverstone',   3.23),
  FuelUsageType('lamborghini_huracan_gt3_evo', 'Paul_Ricard',   3.20),
  FuelUsageType('lamborghini_huracan_gt3_evo', 'misano',        2.65),
  FuelUsageType('lamborghini_huracan_gt3_evo', 'zandvoort',     2.62),
  FuelUsageType('lamborghini_huracan_gt3_evo', 'Spa',           4.24),
  FuelUsageType('lamborghini_huracan_gt3_evo', 'nurburgring',   3.04),
  FuelUsageType('lamborghini_huracan_gt3_evo', 'hungaroring',   2.62),
  FuelUsageType('lamborghini_huracan_gt3_evo', 'barcelona',     2.85),
  FuelUsageType('lamborghini_huracan_gt3_evo', 'zolder',        2.51),
  FuelUsageType('lamborghini_huracan_gt3_evo', 'mont_panorama', 4.00),
  FuelUsageType('lamborghini_huracan_gt3_evo', 'Laguna_Seca',   2.70),
  FuelUsageType('lamborghini_huracan_gt3_evo', 'Suzuka',        3.80),
  FuelUsageType('lamborghini_huracan_gt3_evo', 'Kyalami',       2.85),

  FuelUsageType('lamborghini_huracan_st', 'monza',         3.40),
  FuelUsageType('lamborghini_huracan_st', 'Brands_Hatch',  2.90),
  FuelUsageType('lamborghini_huracan_st', 'Silverstone',   3.40),
  FuelUsageType('lamborghini_huracan_st', 'Paul_Ricard',   3.30),
  FuelUsageType('lamborghini_huracan_st', 'misano',        2.70),
  FuelUsageType('lamborghini_huracan_st', 'zandvoort',     2.70),
  FuelUsageType('lamborghini_huracan_st', 'Spa',           4.30),
  FuelUsageType('lamborghini_huracan_st', 'nurburgring',   3.20),
  FuelUsageType('lamborghini_huracan_st', 'hungaroring',   2.70),
  FuelUsageType('lamborghini_huracan_st', 'barcelona',     2.90),
  FuelUsageType('lamborghini_huracan_st', 'zolder',        2.60),
  FuelUsageType('lamborghini_huracan_st', 'mont_panorama', 4.00),
  FuelUsageType('lamborghini_huracan_st', 'Laguna_Seca',   2.70),
  FuelUsageType('lamborghini_huracan_st', 'Suzuka',        3.80),
  FuelUsageType('lamborghini_huracan_st', 'Kyalami',       2.90),

  FuelUsageType('lexus_rc_f_gt3', 'monza',         3.50),
  FuelUsageType('lexus_rc_f_gt3', 'Brands_Hatch',  2.93),
  FuelUsageType('lexus_rc_f_gt3', 'Silverstone',   3.44),
  FuelUsageType('lexus_rc_f_gt3', 'Paul_Ricard',   3.44),
  FuelUsageType('lexus_rc_f_gt3', 'misano',        2.75),
  FuelUsageType('lexus_rc_f_gt3', 'zandvoort',     2.79),
  FuelUsageType('lexus_rc_f_gt3', 'Spa',           4.23),
  FuelUsageType('lexus_rc_f_gt3', 'nurburgring',   3.24),
  FuelUsageType('lexus_rc_f_gt3', 'hungaroring',   2.79),
  FuelUsageType('lexus_rc_f_gt3', 'barcelona',     2.93),
  FuelUsageType('lexus_rc_f_gt3', 'zolder',        2.70),
  FuelUsageType('lexus_rc_f_gt3', 'mont_panorama', 3.90),
  FuelUsageType('lexus_rc_f_gt3', 'Laguna_Seca',   2.60),
  FuelUsageType('lexus_rc_f_gt3', 'Suzuka',        3.70),
  FuelUsageType('lexus_rc_f_gt3', 'Kyalami',       2.93),

  FuelUsageType('mclaren_650s_gt3', 'monza',         3.45),
  FuelUsageType('mclaren_650s_gt3', 'Brands_Hatch',  2.95),
  FuelUsageType('mclaren_650s_gt3', 'Silverstone',   3.42),
  FuelUsageType('mclaren_650s_gt3', 'Paul_Ricard',   3.42),
  FuelUsageType('mclaren_650s_gt3', 'misano',        2.80),
  FuelUsageType('mclaren_650s_gt3', 'zandvoort',     2.85),
  FuelUsageType('mclaren_650s_gt3', 'Spa',           4.15),
  FuelUsageType('mclaren_650s_gt3', 'nurburgring',   3.20),
  FuelUsageType('mclaren_650s_gt3', 'hungaroring',   2.85),
  FuelUsageType('mclaren_650s_gt3', 'barcelona',     2.95),
  FuelUsageType('mclaren_650s_gt3', 'zolder',        2.60),
  FuelUsageType('mclaren_650s_gt3', 'mont_panorama', 4.00),
  FuelUsageType('mclaren_650s_gt3', 'Laguna_Seca',   2.70),
  FuelUsageType('mclaren_650s_gt3', 'Suzuka',        3.80),
  FuelUsageType('mclaren_650s_gt3', 'Kyalami',       2.95),

  FuelUsageType('mclaren_720s_gt3', 'monza',         3.73),
  FuelUsageType('mclaren_720s_gt3', 'Brands_Hatch',  2.65),
  FuelUsageType('mclaren_720s_gt3', 'Silverstone',   3.55),
  FuelUsageType('mclaren_720s_gt3', 'Paul_Ricard',   3.45),
  FuelUsageType('mclaren_720s_gt3', 'misano',        2.66),
  FuelUsageType('mclaren_720s_gt3', 'zandvoort',     2.66),
  FuelUsageType('mclaren_720s_gt3', 'Spa',           4.10),
  FuelUsageType('mclaren_720s_gt3', 'nurburgring',   3.20),
  FuelUsageType('mclaren_720s_gt3', 'hungaroring',   2.71),
  FuelUsageType('mclaren_720s_gt3', 'barcelona',     2.85),
  FuelUsageType('mclaren_720s_gt3', 'zolder',        2.80),
  FuelUsageType('mclaren_720s_gt3', 'mont_panorama', 4.00),
  FuelUsageType('mclaren_720s_gt3', 'Laguna_Seca',   2.70),
  FuelUsageType('mclaren_720s_gt3', 'Suzuka',        3.80),
  FuelUsageType('mclaren_720s_gt3', 'Kyalami',       2.85),

  FuelUsageType('mercedes_amg_gt3', 'monza',         3.45),
  FuelUsageType('mercedes_amg_gt3', 'Brands_Hatch',  2.93),
  FuelUsageType('mercedes_amg_gt3', 'Silverstone',   3.45),
  FuelUsageType('mercedes_amg_gt3', 'Paul_Ricard',   3.33),
  FuelUsageType('mercedes_amg_gt3', 'misano',        2.76),
  FuelUsageType('mercedes_amg_gt3', 'zandvoort',     2.64),
  FuelUsageType('mercedes_amg_gt3', 'Spa',           4.05),
  FuelUsageType('mercedes_amg_gt3', 'nurburgring',   3.16),
  FuelUsageType('mercedes_amg_gt3', 'hungaroring',   2.64),
  FuelUsageType('mercedes_amg_gt3', 'barcelona',     2.93),
  FuelUsageType('mercedes_amg_gt3', 'zolder',        2.50),
  FuelUsageType('mercedes_amg_gt3', 'mont_panorama', 4.20),
  FuelUsageType('mercedes_amg_gt3', 'Laguna_Seca',   2.70),
  FuelUsageType('mercedes_amg_gt3', 'Suzuka',        2.93),
  FuelUsageType('mercedes_amg_gt3', 'Kyalami',       2.93),

  FuelUsageType('nissan_gt_r_gt3_2018', 'monza',         3.55),
  FuelUsageType('nissan_gt_r_gt3_2018', 'Brands_Hatch',  2.90),
  FuelUsageType('nissan_gt_r_gt3_2018', 'Silverstone',   3.45),
  FuelUsageType('nissan_gt_r_gt3_2018', 'Paul_Ricard',   3.45),
  FuelUsageType('nissan_gt_r_gt3_2018', 'misano',        2.80),
  FuelUsageType('nissan_gt_r_gt3_2018', 'zandvoort',     2.85),
  FuelUsageType('nissan_gt_r_gt3_2018', 'Spa',           4.25),
  FuelUsageType('nissan_gt_r_gt3_2018', 'nurburgring',   3.30),
  FuelUsageType('nissan_gt_r_gt3_2018', 'hungaroring',   2.85),
  FuelUsageType('nissan_gt_r_gt3_2018', 'barcelona',     2.90),
  FuelUsageType('nissan_gt_r_gt3_2018', 'zolder',        2.70),
  FuelUsageType('nissan_gt_r_gt3_2018', 'mont_panorama', 3.95),
  FuelUsageType('nissan_gt_r_gt3_2018', 'Laguna_Seca',   2.70),
  FuelUsageType('nissan_gt_r_gt3_2018', 'Suzuka',        3.75),
  FuelUsageType('nissan_gt_r_gt3_2018', 'Kyalami',       2.90),

  FuelUsageType('porsche_991ii_gt3_cup', 'monza',         3.50),
  FuelUsageType('porsche_991ii_gt3_cup', 'Brands_Hatch',  2.86),
  FuelUsageType('porsche_991ii_gt3_cup', 'Silverstone',   3.50),
  FuelUsageType('porsche_991ii_gt3_cup', 'Paul_Ricard',   3.50),
  FuelUsageType('porsche_991ii_gt3_cup', 'misano',        2.86),
  FuelUsageType('porsche_991ii_gt3_cup', 'zandvoort',     2.86),
  FuelUsageType('porsche_991ii_gt3_cup', 'Spa',           4.20),
  FuelUsageType('porsche_991ii_gt3_cup', 'nurburgring',   3.20),
  FuelUsageType('porsche_991ii_gt3_cup', 'hungaroring',   2.86),
  FuelUsageType('porsche_991ii_gt3_cup', 'barcelona',     2.86),
  FuelUsageType('porsche_991ii_gt3_cup', 'zolder',        2.86),
  FuelUsageType('porsche_991ii_gt3_cup', 'mont_panorama', 4.00),
  FuelUsageType('porsche_991ii_gt3_cup', 'Laguna_Seca',   2.20),
  FuelUsageType('porsche_991ii_gt3_cup', 'Suzuka',        2.86),
  FuelUsageType('porsche_991ii_gt3_cup', 'Kyalami',       2.86),

  FuelUsageType('porsche_991ii_gt3_r', 'monza',         3.66),
  FuelUsageType('porsche_991ii_gt3_r', 'Brands_Hatch',  2.73),
  FuelUsageType('porsche_991ii_gt3_r', 'Silverstone',   3.80),
  FuelUsageType('porsche_991ii_gt3_r', 'Paul_Ricard',   3.61),
  FuelUsageType('porsche_991ii_gt3_r', 'misano',        2.73),
  FuelUsageType('porsche_991ii_gt3_r', 'zandvoort',     3.80),
  FuelUsageType('porsche_991ii_gt3_r', 'Spa',           3.80),
  FuelUsageType('porsche_991ii_gt3_r', 'nurburgring',   2.80),
  FuelUsageType('porsche_991ii_gt3_r', 'hungaroring',   2.80),
  FuelUsageType('porsche_991ii_gt3_r', 'barcelona',     2.73),
  FuelUsageType('porsche_991ii_gt3_r', 'zolder',        2.73),
  FuelUsageType('porsche_991ii_gt3_r', 'mont_panorama', 2.73),
  FuelUsageType('porsche_991ii_gt3_r', 'Laguna_Seca',   2.80),
  FuelUsageType('porsche_991ii_gt3_r', 'Suzuka',        3.80),
  FuelUsageType('porsche_991ii_gt3_r', 'Kyalami',       2.80),
];